### PR TITLE
fix: cancel button on import

### LINKED ISSUE #996: nit: Cancel button doesn't work on Ingest Document page
But the user can use the browser's back arrow to back out of the page

### PR DESCRIPTION
**Pull request by rudimatz**
fix https://github.com/ietf-tools/purple/issues/1086 and fix https://github.com/ietf-tools/purple/issues/996 and fix storing title on import

### CODE REVIEW

File: client/app/pages/docs/import.vue [hunk 1]
```diff
@@ -120,7 +120,7 @@
     </div>
 
     <div class="mt-6 flex items-center justify-end gap-x-6">
-      <BaseButton btn-type="cancel">Cancel</BaseButton>
+      <BaseButton btn-type="cancel" @click="navigateTo('/queue/submissions')">Cancel</BaseButton>
```
Comment (holloway) [inline client/app/pages/docs/import.vue]: Do we have a `const` from urls for this path?

should the path have a trailing slash?

Comment (rudimatz) [reply client/app/pages/docs/import.vue]: the link via UI brings me to http://localhost:8088/queue/submissions
Do you think we should create a constant for this? It is basically just directing to the `submission` tab.

Comment (holloway) [reply client/app/pages/docs/import.vue]: Although we're not doing it consistently, I think all URLs should have an entry in `urls.ts` rather than strings in lots of disparate files. The _link via UI_ will be another copy of that string so we should consolidate imo.

I guess the question of whether it should have a trailing slash is a broader question of Purple so I'm happy to ignore that for now.

Comment (rudimatz) [reply client/app/pages/docs/import.vue]: I see, you mean like QUEUE_QUEUE_PATH?

**Review by holloway — APPROVED** [review]
